name: Build Yuurigram

on:
  push:
    branches: [ "master", "main" ]
  pull_request:
    branches: [ "master", "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Setup Android SDK & NDK
        uses: android-actions/setup-android@v3

      - name: Install NDK
        run: sdkmanager "ndk;21.4.7075529"

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y gperf yasm cmake ninja-build golang-go

      - name: Create Secrets File
        run: |
          echo "APP_ID=${{ secrets.APP_ID }}" > secrets_for_ci.env
          echo "APP_HASH=${{ secrets.APP_HASH }}" >> secrets_for_ci.env
          echo "APP_ID=${{ secrets.APP_ID }}" >> gradle.properties
          echo "APP_HASH=${{ secrets.APP_HASH }}" >> gradle.properties

      - name: Permissions
        run: chmod +x gradlew

      - name: Clean Gradle cache
        run: ./gradlew clean

      - name: Build
        run: ./gradlew assembleAfatDebug --stacktrace
        env:
          APP_ID: ${{ secrets.APP_ID }}
          APP_HASH: ${{ secrets.APP_HASH }}

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: Yuurigram-Debug
          path: TMessagesProj_App/build/outputs/apk/afat/debug/*.apk